server:
  port: 8080
greeting-service:
  greeting: "Hello"
  default-value: "World"
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always